name: Update Comment with Webhook Response on Pull Request

on:
  pull_request: # Trigger the workflow on pull request events
    types:
      - opened
      - synchronize
      - reopened

jobs:
  handle_webhook_response:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Webhook and Capture Response
      id: trigger_webhook
      run: |
        # Replace this URL with your actual webhook URL
        WEBHOOK_URL="https://test-server-4cso57atl-emmyaris-projects.vercel.app/api"
        COOKIE="JSESSIONID=635BEA21E9EF04616134E7C64444B54C; glide_node_id_for_js=2729d31b698a76c9eeea7ce6af66c87e8c10cf01978362f14141f6cb3b41c8da; glide_user_route=glide.f42cc9703de7303a619d6b47ab989a15"
        
        RESPONSE=$(curl -v -s -X POST $WEBHOOK_URL  -b "$COOKIE" -H "Content-Type: application/json")
        
    - name: Post Comment on Pull Request
      if: ${{ success() }} # Only run if the previous step was successful
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr_number = context.payload.pull_request.number; // Use the PR number from the context
          const responseMessage = process.env.response;

          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr_number, // Comment on the specific PR
            body: `Webhook processed successfully: ${responseMessage}`,
          });
